### PR TITLE
Add a .desktop file and install target for Linux

### PR DESCRIPTION
**Pull request by apetresc**
This adds an `install` target that Linux users can use with the typical `sudo make install` flow to install goreviewpartner to `/opt/goreviewpartner`, together with an icon and `.desktop` file entry so that it can be accessed from any XDG-compatible desktop menu  or launcher, like so:

Once GRP has the ability to take an argument on the command-line to open up an SGF or RSGF directly, this can easily be added as a `MimeType` key to the `.desktop` file to set up the association automatically. This is a necessary prerequisite to resolving #45 on Linux.

### CODE REVIEW

**Comment by pnprog** [comment]
Thanks for thePR, this is so cool :)

> Once GRP has the ability to take an argument on the command-line to open up an SGF or RSGF directly, this can easily be added as a MimeType key to the .desktop file to set up the association automatically. 

At the moment, it is possible to open a RSGF file from command line, using something like:

`python dual_view.py mygame.rsgf`

What would then be necessary to set up the association automatically?

**Comment by apetresc** [comment]
Ooh interesting.

So the problem is that a `.desktop` file can't really specify one executable (`python main.py`) for opening up standalone, and a different one (`python dual_view.py`) for opening up the associated file. So we have three options:

1. Create a wrapper shell script that picks the right "mode" to run, and set that as the `.desktop` entry
2. Add whatever functionality is necessary to `main.py` to just redirect to `dual_view.py` in the presence of the right arg
3. Have two separate `.desktop` files, one for standalone and one for opening SGFs (I don't think this last option is a very good idea, just listing it out for the sake of completeness)

What do you think, @pnprog? I'm leaning towards 1) but you know best of course :)

**Comment by pnprog** [comment]
I also think option 2 is better.

In fact it is certainly easy to do it when running from python source, but it might be more tricky for the "compiled" version I prepare for download. I will check how this can be done.

**Comment by pnprog** [comment]
I think most users would be upset if GRP is set as default software to handle SGF files (instead of gogui or sabaki I mean), but it is certainly ok for RSGF file. Having GRP as a second choice for SGF ("Open with" in the right click menu) would be better for SGF.

Then, based on the file extension, GRP would propose an analysis (for SGF) or a review for RSGF.

**Comment by apetresc** [comment]
To be clear, a .desktop file can't set a user's associations for them - it can only declare itself capable of handling a particular mime type. It's up to whatever desktop environment the user is using to actually set default associations (although if there's only one program registered for a particular mime-type, like would probably happen for RSGF, most of them default to associating that one).

So there shouldn't be any harm to adding associations for both sgf and rsgf. However, RSGF is not a standard XDG extension so we will need to ship a MIME-type XML file for it as well, so the system knows it exists at all. I'll file that in a separate PR.

**Comment by pnprog** [comment]
Hi @apetresc ,

I have just made it possible to open SGF or RSGF file directly for **main.py**

**Pull request merged**
