### PR TITLE
Fixed layout on main window.

### PR DESCRIPTION
**Pull request by bsloane1650**
Fixed layout on main window so that buttons appear in front of logo when they overlap.

### CODE REVIEW

**Comment by bsloane1650** [comment]
Old behaviour: old
New behaviour: new

Tested on a tiling window manager (XMonad).

**Comment by pnprog** [comment]
Nice!

Was the older layout somewhat an issue for you? maybe to high for your screen size?

Thanks for the patch!

**Comment by pnprog** [comment]
Ho, I see, maybe XMonad was compressing the windows to arrange it with other windows?
(I am checking XMonad on Wikipedia right now)

**Comment by bsloane1650** [comment]
Yeah. The old layout initially made it unusable for me, as I did not realize that there were even other buttons.

What was happening was that the logo was expanding to fill in the X-dimension. The problem was actually coming from XMonad expanding the window to fill up the available space.

The "correct" solution would probably be for the window to request to be started in float mode with the correct dimensions, and to not be resized to "bad" dimensions. I have no idea how to actually do this, but some applications seem to do so (for instance, the KGS cgoban client). However, as long as it is usable, I doubt any tiling WM user would complain that the splash screen tiles.

**Pull request merged**
