### PR TITLE
add helpful default profile configs phoenixgo

### PR DESCRIPTION
**Pull request by wonderingabout**
these can be modified if needed

but they should help a lot people to set up their grp and phoenixgo

see FAQ question for syntax error help : 

https://github.com/wonderingabout/PhoenixGo/tree/faqv2-bazel-master#a4-syntax-error-windows

### CODE REVIEW

**Comment by wonderingabout** [comment]
@pnprog 

#99

**Comment by wonderingabout** [comment]
note that i set time to 120s, but it is much faster on my gtx1060 powercapped at 75W (20s per move)

**Comment by pnprog** [comment]
> note that i set time to 120s, but it is much faster on my gtx1060 powercapped at 75W (20s per move)

This could be because `early_stop` is enabled.

I need your help (again!) to check something: what happens if you try to run your version of PhoenixGo (that is compiled with GPU support) by providing it a CPU only config file, with something like `--config_path=etc/mcts_cpu.conf` ? does it still somehow works, but run only with CPU?

**Comment by wonderingabout** [comment]
@pnprog 

no idea what happens lol, but it's not needed

i just forgot about the cpu grp conf file

and as i messaged you just now in the other topic, the grp files have unlimited and infinite time, see :+1: 

https://github.com/Tencent/PhoenixGo/issues/86#issuecomment-458983774

**Comment by wonderingabout** [comment]
for this PR, i will add a profile for CPU too :+1: 

dont merge yet :+1:

**Comment by pnprog** [comment]
> I need your help (again!) to check something: what happens if you try to run your version of PhoenixGo (that is compiled with GPU support) by providing it a CPU only config file, with something like --config_path=etc/mcts_cpu.conf ? does it still somehow works, but run only with CPU?

> no idea what happens lol, but it's not needed

I fact, yes, I would like to check this: for the bots default command line parameters in the source code of GRP, I want to have parameters that are guaranteed to work on first time, even with degraded performances:
+ So I would prefer to have **--config_path=etc/mcts_cpu.conf** as default, if it work _out of the box_ for both users of CPU/GPU/CUDA... then it's up to the user to tune it better afterwards.
+ Then, I will prepare download zip for CPU, and GPU, and CUDA with appropriate config files.
+ And then, I will explain as much as necessary in the GRP documentation what are the points to follow.

I used to do that for the old version of Ray, when there was only one binary for both CPU and GPU. I used to have **--no-gpu** as the default command line parameter.

I think that 90% of GRP users will download the windows ready versions of GRP with the bot they plan to use, so they will be OK
Then the 10% remaining users are more tech savvy users (windows users that run GRP from python, or Linux/Mac users). They would be able to run it with the default settings (even if at reduced performance) and I am confident they can either figure out how to improve the situation, or read the documentation.

Beside, as long as PhoenixGo team does not accept the PR (which we have no guarantees they will), then I cannot really put **--config_path=etc/mcts_cpu_grp.conf** as default parameters, this one would be guaranteed to not work.

**Comment by wonderingabout** [comment]
i dont like this idea @pnprog 

i think we are creating a new thing here, so its up to us to make so that every user runs in optimal settings as clearly and smoothly as possible, and if too hard find easily help

i'd rather create many different config files pre-available, with example profiles easy to modify, and maybe link to a quick documentation that i can write if needed

also looking at the files they are really different : 

- gpu tensorrt : no matter what we do this will work only on linux with tensorrt : 
https://github.com/wonderingabout/PhoenixGo/blob/faqv2-bazel-master/etc/mcts_1gpu_grp.conf
- gpu notensorrt : this will work on windows or linux (no mac gpu support), i provided 2 profiles to show how to integrate windows and linux path differently (syntax errors)
- cpu : this will work on windows and linux, but again the syntax for windows or linux is different and tricky, so i added it here in 2 different profiles 


also i answered you here for the git question :100: 
https://github.com/Tencent/PhoenixGo/issues/86#issuecomment-459753545

hope i helped, dont hesitate to criticize me if disagree lol :1st_place_medal:

**Comment by pnprog** [comment]
Haha, let's agree to disagree then :)

But I am ok to make an exception for PhoenixGo, considering  it is quite tricky to configure.

What I will do:

+ for the time being, I will create one entry per **.conf** already in the **etc/** folder (maybe with a  limit to one GPU max).
+ then, when the PR is accepted by the PhoenixGo team, I will replace those entries with entries pointing to the **grp_.conf** files.

If that's ok with you, I will let you go ahead with the PR for PhoenixGo, I have a limited time frame where I can spend time on programming (basically until the end of my holidays) and I am rushing to release a new version of GRP in time (my todo list is long), so I don't want to spend too much time figuring out how all those branches are working.

(plus, the internet connexion sucks here)

**Comment by pnprog** [comment]
By the way, I added a new category of graph "Reading depth":
2019-02-02-000547_787x301_scrot
Only PhoenixGo proposes this for now :)

**Comment by wonderingabout** [comment]
and for the PR as i said in the tencent github just PR to my branch, i'll merge it to my branch :+1: , much faster

take your time and rest if needed or short time though lol

**Comment by wonderingabout** [comment]
@pnprog 

i hope it's good now :+1:

**Comment by pnprog** [comment]
Thanks for the commit!

**Comment by wonderingabout** [comment]
welcome :+1: 

glad it helps :+1:

**Pull request merged**
