### PR TITLE
Replace tkinter's askfileopen dialog with wx's, for better UX

### PR DESCRIPTION
**Pull request by fishcu**
I changed the file dialogs used to use wx instead of tkinter, as they were driving me crazy.
Wx has these advantages for me:
- Set default directory to home (should also be possible with tkinter)
- Native scaling for UI elements. Tkinter looks tiny on my high resolution display (Ubuntu 16.04).
- File dialog close to what you expect from a native application (quick access directories on the left, support scrolling with mouse wheel, search by typing on the keyboard, and so on)

### CODE REVIEW

**Comment by fishcu** [comment]
BTW, I didn't change the dialogs in the *_analysis.py source yet. If you agree to merge, I would put the necessary code into a separate file to avoid code bloating.

**Comment by fishcu** [comment]
FWIW, wx comes pre-installed on my elementary OS (used for testing this pull request), whereas tkinter did not. Maybe it's worth switching to wx completely in the long run?

**Comment by pnprog** [comment]
Hi!

Thanks for the pull request, I agree that tkinter dialogs are terrible!

My concern about wx is that I want to keep the "installation" process easy on Windows, something simple like download, extract and run (no pip install or other complicated things). That's why I am stuck with python2 because py2exe works well. I will need to check if wx and py2exe work well together.

FWIW, neither tkinter or wx came pre-installed on my Ubuntu. tkinter is part of the standard installation on windows, but I don't know about wx.

I think the best solution will be to "wrap" those tkFileDialog and wx.FileDialog into dedicated functions, something similar to what I did with show_info() and show_error(). Let's say open_file() and save_file(). Then to have something like:

```
try:
    import wx
    def open_file():
        ...
    def save_file():
        ....
except:
    #cannot load wx, fallback to tk
    def open_file():
        ...
    def save_file():
        ...
```

I will accept your pull request, just give me some time to figure out how to do this: it's my very first time I am faced with a pull request, and I am about to push a pretty big commit with code changes all over the place. I need to check the git documentation to see how to deal with the potential conflicts.

**Comment by pnprog** [comment]
I just downloaded the wx package (29Mo) and indeed, the dialog are much better, in fact, they are the same as the system dialog.

**Comment by fishcu** [comment]
You can "request changes" to this pull request. For example, you could ask me to make wrapper functions (something that I intended anyway).

**Comment by pnprog** [comment]
Ha ok, then I propose that I first push that big commit of mine (it is now ready) then I implement those wrapper functions for Tkinter (give me 2 hours).

Then I let you add their equivalent for wx.

**Comment by pnprog** [comment]
Ok, I just made the wrapper functions for tkFileDialog functions (3 functions at the end of **toolbox.py**). I let you pull a request to add the equivalent for wx.

**Comment by fishcu** [comment]
Couldn't figure out how to keep this previous branch, that's why I deleted it and created a new one :p I'll get better at git eventually!

**Pull request closed without merging**
